### ISSUE TITLE
About Keypoint Resize

### ISSUE THREAD

**Issue by liangying-Ke** [500swapnil/stacked-hourglass#3]
Question :
While the image resizing, the coordinate of keypoints does not seem to be change.
Are the keypoints labeled in the 64x64 size of image?

**Comment by 500swapnil** [comment]
Yes. Currently, it expects keypoints in the 64x64 size. I will be adding support for different sizes when I can complete training on MPII dataset.

**Comment by liangying-Ke** [comment]
OK, Thanks you for the answer.
